# Generated by Django 5.2.13 on 2026-08-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_analysishistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslog',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
