# Generated by Django 5.2.13 on 2026-08-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_newslog_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('input_type', models.CharField(max_length=20)),
                ('url', models.TextField(blank=True)),
                ('article', models.TextField(blank=True)),
                ('prediction', models.CharField(max_length=20)),
                ('trust_score', models.FloatField()),
                ('bias_score', models.FloatField()),
                ('source_score', models.FloatField()),
                ('similarity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
