# Generated by Django 5.2.13 on 2026-08-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_visitorlog_alter_predictionhistory_table_loginlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='article_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='groq_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prediction_images/'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='image_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='lime_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='publish_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='similarity_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='source_bias_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='source_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='uploaded_file',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
