# Generated by Django 5.2.13 on 2026-08-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_predictionhistory_ai_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
    ]
