# Generated by Django 5.2.13 on 2026-09-17 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_predictionhistory_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect')], max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('WRONG_PREDICTION', 'Wrong prediction'), ('CONTEXT_MISUNDERSTOOD', 'Context misunderstood'), ('SOURCE_INFORMATION', 'Source information incorrect'), ('INSUFFICIENT_INFORMATION', 'Insufficient information'), ('OTHER', 'Other')], max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('predicted_label', models.CharField(max_length=20)),
                ('prediction_confidence', models.FloatField(default=0.0)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('verified_label', models.CharField(blank=True, choices=[('Real News', 'Real News'), ('Fake News', 'Fake News')], max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='detector.newslog')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prediction_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prediction_feedback',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('prediction', 'user'), name='unique_feedback_per_user_prediction')],
            },
        ),
    ]
